# Add your additional Hyprland configurations here

gesture = 3, horizontal, resize
gesture = 3, down, float
gesture = 3, up, fullscreen
gesture = 4, horizontal, workspace
gesture = 4, down, close

$mainMod = SUPER
$HYPRSCRIPTS = ~/.config/hypr/scripts

bind = $mainMod SHIFT, C, exec, $HYPRSCRIPTS/screenshot.sh --instant-copy-area
bind = $mainMod, semicolon, exec, rofi -show emoji -modi emoji
