# In HyperMode have included configuration touchpad
gesture = 3, horizontal, workspace
gesture = 3, up, float
gesture = 3, down, close
gesture = 4, horizontal, resize

# Using HyprMode with add keybindings
[ CTRL + SHIFT + E ]
rofi -show emoji -modi emoji
[ CTRL + ALT + C ]
grimblast copy area 
[ CTRL + ALT + S ]
grimblast copysave area ~/Pictures/Screenshots/$(date +%Y%m%d-%H%M%S).jpg